services:
  - type: web
    name: cluster
    branch: master
    plan: pro
    dockerfilePath: ./Dockerfile
    repo: https://github.com/greatautomate/BotClusters
    env: docker
    envVars:
      - key: CLUSTER_01
        sync: false
    autoDeploy: false
